#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1562150140                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : in                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://ashutoshbilla.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Camera with Manual Controls

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ashutosh Billa
your_link                                 : https://ashutoshbilla.com
your_city                                 : Hyderabad
email_address                             : appsbyab@gmail.com
facebook_username                         :
instagram_username                        :
twitter_username                          : ashutoshbilla
github_username                           : ashutoshbilla
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Manual Controls
    description                           : Change settings like Shutter Speed, ISO, Focus, and White Balance by swiping on the controls.
    fontawesome_icon_name                 : camera-alt

  - title                                 : Grid
    description                           : Use grids like rule of thirds, golden ratio, and square to compose your perfect shot.
    # fontawesome_icon_name                 : mobile

  - title                                 : Output Format
    description                           : Pick your choice of output file format from JPEG, HEIF, RAW, and RAW+JPEG. ProRAW coming soon.
    # fontawesome_icon_name                 : play-circle

  - title                                 : Lock Settings
    description                           : When you find the right camera settings for your shot you can tap the lock button to lock all the controls like the shutter speed, ISO, focus, and white balance to avoid accidentally disturbing your settings.
    # fontawesome_icon_name                 : sync

  - title                                 : Exposure Bracketing
    description                           : Capture three photos with varying levels of exposure that you set and later blend parts of each photo to create one perfect photo.
    # fontawesome_icon_name                 : adjust

  - title                                 : Geotagging
    description                           : Enabled location geotagging to save your current location to your photos' metadata.
    fontawesome_icon_name                 : map-marker-alt

  - title                                 : View Metadata
    description                           : View the metadata of your photos' like the settings at the time of capturing the photo, edit history, different versions of the photo and their file size.
    fontawesome_icon_name                 : info-circle

  - title                                 : Share
    description                           : You can share a specific version of your photo from the edit history or different version like original, edited or RAW version.
    fontawesome_icon_name                 : share-alt

  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle

  # - title                                 : # New Feature Title
  #   description                           : # New Feature Description
  #   fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
